name: fork project

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: fork project
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Push
        run: |
          git remote add openwrt https://github.com/openwrt/openwrt.git
          git fetch -t openwrt
          git push --tags origin "refs/remotes/openwrt/*:refs/heads/*"
