name: Test Action

on:
  workflow_dispatch:
    inputs:
      dockerhub:
        description: 'Push to Docker Hub'
        required: false
        type: boolean
      platforms:
        description: 'Target platforms, default "linux/amd64,linux/arm64"'
        required: true
        default: 'linux/amd64,linux/arm64'

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Output Array
        uses: actions/github-script@v7
        id: set-array
        with:
          script: |
            console.log(${{ inputs.dockerhub }})
            if (${{ inputs.dockerhub }}) {
              return ["a", "b"]
            } else {
              return ["b"]
            }

      - name: Dump Array
        env:
          ARRAY: ${{ toJson(fromJson(steps.set-array.outputs.result)) }}
        run: echo "$ARRAY"
