name: Test Action

on:
  workflow_dispatch:
    inputs:
      dockerhub:
        description: 'Push to Docker Hub'
        required: false
        type: boolean
      platforms:
        description: 'Target platforms, default "linux/amd64,linux/arm64"'
        required: true
        default: 'linux/amd64,linux/arm64'

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Output Array
        uses: actions/github-script@v7
        id: set-array
        with:
          result-encoding: string
          script: |
            console.log(${{ inputs.dockerhub }});
            const images = ["a"];
            if (${{ inputs.dockerhub }}) {
              images.push("b");
            }
            return images.join('\n');

      - name: Dump Array
        env:
          ARRAY: ${{ steps.set-array.outputs.result }}
        run: echo "$ARRAY"
