name: Self writing

on:
  watch:
    types: [started]

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check
        run: pwd && ls -la

