name: Self writing

on:
  watch:
    types: [started]

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Count
        run: expr $(cat count)  + 1 > count
      - name: Submit
        run: |
          git config --global user.name "Actions"
          git config --global user.email "actions@github.com"
          git add count && git commit -m 'update count' && git push

