name: Self writing

on:
  watch:
    types: [started]

jobs:
  update:
    name: Update
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - name: Env
        env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_NAME
          echo $EVENT

      - name: Test pipe
        run: |
          false || bash -c 'set -o pipefail ; false | true'


