name: Self writing

on:
  watch:
    types: [started]

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Count
        run: expr $(cat count)  + 1 > count
      - name: Submit
        run: |
          git config --global user.name "Actions"
          git config --global user.email "actions@github.com"
          git add count && git commit -m 'update count' && git push
      - name: Fetch CDN
        uses: actions/checkout@v2
        with:
          repository: jjm2473/cdn
          fetch-depth: 2
          path: cdn
      - name: Push CDN
        run: |
          git config --global user.name "Actions"
          git config --global user.email "actions@github.com"
          echo test > cdn/test.txt
          git -C cdn add --all
          git -C cdn commit -m 'release'
          git -C cdn push
  

